//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContext : DbContext
    {
        public ModelContext()
            : base("name=ModelContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<ciudad> ciudad { get; set; }
        public virtual DbSet<cuentadigital> cuentadigital { get; set; }
        public virtual DbSet<curso_alumno> curso_alumno { get; set; }
        public virtual DbSet<materia> materia { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<post> post { get; set; }
        public virtual DbSet<post_respuesta> post_respuesta { get; set; }
        public virtual DbSet<profesor_materia> profesor_materia { get; set; }
        public virtual DbSet<provincia> provincia { get; set; }
        public virtual DbSet<streaming> streaming { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipo_de_curso> tipo_de_curso { get; set; }
        public virtual DbSet<video> video { get; set; }
        public virtual DbSet<carrera> carrera { get; set; }
        public virtual DbSet<universidad> universidad { get; set; }
        public virtual DbSet<academia> academia { get; set; }
        public virtual DbSet<curso> curso { get; set; }
    }
}
