//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class curso_alumno
    {
        public int idcurso { get; set; }
        public string idalumno { get; set; }
        public System.DateTime fecha_inscripcion { get; set; }
        public System.DateTime fecha_fin { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual curso curso { get; set; }
    }
}
