//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class profesor_materia
    {
        public string idprofesor { get; set; }
        public int idmateria { get; set; }
        public System.DateTime fecha_alta { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual materia materia { get; set; }
    }
}
